package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/chordpli/tmula/server/internal/importer"
	"github.com/chordpli/tmula/server/internal/scenariofile"
)

// initScenario implements `tmula init`: scaffold a scenario file from an
// existing API description (OpenAPI or HAR) so the user starts from their real
// endpoints instead of a blank page.
func initScenario(args []string) error {
	fs := flag.NewFlagSet("tmula init", flag.ContinueOnError)
	var (
		from   = fs.String("from", "", "API description to import: an OpenAPI or HAR file")
		format = fs.String("format", "auto", "input format: auto | openapi | har")
		out    = fs.String("out", "", "write the scenario here (default: stdout)")
		target = fs.String("target", "", "override the target base URL")
	)
	fs.Usage = func() {
		fmt.Fprint(os.Stderr, "usage: tmula init --from <openapi.yaml|session.har> [--out scenario.yaml]\n\n")
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *from == "" {
		fs.Usage()
		return fmt.Errorf("--from is required")
	}

	data, err := os.ReadFile(*from)
	if err != nil {
		return fmt.Errorf("read %q: %w", *from, err)
	}
	sc, err := importScenario(data, *format, *from)
	if err != nil {
		return err
	}
	if *target != "" {
		sc.Target = *target
	}
	if sc.Target == "" {
		return fmt.Errorf("could not determine a target URL from the input; pass --target")
	}

	doc, err := importer.Marshal(sc)
	if err != nil {
		return err
	}
	header := "# Generated by `tmula init` from " + filepath.Base(*from) + ".\n" +
		"# Review the steps (fill in path params and bodies), then:  tmula run <this file>\n"
	doc = append([]byte(header), doc...)

	if *out == "" {
		_, err = os.Stdout.Write(doc)
		return err
	}
	if err := os.WriteFile(*out, doc, 0o644); err != nil {
		return fmt.Errorf("write %q: %w", *out, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d steps) — run it with:  tmula run %s\n", *out, len(sc.Flow), *out)
	return nil
}

// importScenario dispatches to the right importer for the input format.
func importScenario(data []byte, format, name string) (scenariofile.Scenario, error) {
	switch detectFormat(format, name, data) {
	case "openapi":
		return importer.FromOpenAPI(data)
	case "har":
		return importer.FromHAR(data)
	default:
		return scenariofile.Scenario{}, fmt.Errorf("unknown format %q; use --format openapi|har", format)
	}
}

// detectFormat resolves an explicit --format, else infers it from the filename
// extension and finally the content. A HAR is JSON with a top-level "log" object
// holding an "entries" array; OpenAPI/Swagger has "openapi"/"swagger"/"paths".
// Content sniffing is structural (parse the JSON and inspect keys) so it is
// robust to whitespace and key order — a real browser HAR was being misread as
// OpenAPI when uploaded without its .har name. A substring guess remains as a
// last resort for non-JSON (YAML) OpenAPI.
func detectFormat(format, name string, data []byte) string {
	if format != "" && format != "auto" {
		return format
	}
	if strings.HasSuffix(strings.ToLower(name), ".har") {
		return "har"
	}
	var probe struct {
		Log *struct {
			Entries []json.RawMessage `json:"entries"`
		} `json:"log"`
		OpenAPI json.RawMessage            `json:"openapi"`
		Swagger json.RawMessage            `json:"swagger"`
		Paths   map[string]json.RawMessage `json:"paths"`
	}
	if json.Unmarshal(data, &probe) == nil {
		// Check the OpenAPI markers first: a real OpenAPI doc never carries a
		// top-level log/entries, so this keeps a (pathological) spec that happens
		// to mention one from being mistaken for a HAR.
		switch {
		case len(probe.OpenAPI) > 0 || len(probe.Swagger) > 0 || probe.Paths != nil:
			return "openapi"
		case probe.Log != nil && probe.Log.Entries != nil:
			return "har"
		}
	}
	if bytes.Contains(data, []byte(`"log"`)) && bytes.Contains(data, []byte(`"entries"`)) {
		return "har"
	}
	return "openapi"
}
