package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"github.com/chordpli/tmula/server/internal/importer"
	"github.com/chordpli/tmula/server/internal/runspec"
	"github.com/chordpli/tmula/server/internal/scenariofile"
)

// initScenario implements `tmula init`: scaffold a scenario file from an
// existing API description (OpenAPI or HAR) so the user starts from their real
// endpoints instead of a blank page.
func initScenario(args []string) error {
	fs := flag.NewFlagSet("tmula init", flag.ContinueOnError)
	var (
		from   = fs.String("from", "", "input to import: an OpenAPI spec, a HAR capture, or an access log")
		format = fs.String("format", "auto", "input format: auto | openapi | har | accesslog")
		out    = fs.String("out", "", "write the scenario here (default: stdout)")
		target = fs.String("target", "", "override the target base URL")
	)
	fs.Usage = func() {
		fmt.Fprint(os.Stderr, "usage: tmula init --from <openapi.yaml|session.har|access.log> [--out scenario.yaml]\n\n")
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *from == "" {
		fs.Usage()
		return fmt.Errorf("--from is required")
	}

	data, err := os.ReadFile(*from)
	if err != nil {
		return fmt.Errorf("read %q: %w", *from, err)
	}
	sc, note, err := importScenario(data, *format, *from)
	if err != nil {
		return err
	}
	if note != "" {
		fmt.Fprintln(os.Stderr, note)
	}
	if *target != "" {
		sc.Target = *target
	}
	if sc.Target == "" {
		return fmt.Errorf("could not determine a target URL from the input; pass --target")
	}

	doc, err := importer.Marshal(sc)
	if err != nil {
		return err
	}
	review := "# Review the steps (fill in path params and bodies), then:  tmula run <this file>\n"
	count, unit := len(sc.Flow), "steps"
	if sc.Graph != nil {
		review = "# Review the graph (weights are observed transition shares; template paths\n" +
			"# carry sample observed values), then:  tmula run <this file>\n"
		count, unit = len(sc.Graph.Nodes), "nodes"
	}
	header := "# Generated by `tmula init` from " + filepath.Base(*from) + ".\n" + review
	doc = append([]byte(header), doc...)

	if *out == "" {
		_, err = os.Stdout.Write(doc)
		return err
	}
	if err := os.WriteFile(*out, doc, 0o644); err != nil {
		return fmt.Errorf("write %q: %w", *out, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d %s) — run it with:  tmula run %s\n", *out, count, unit, *out)
	return nil
}

// importScenario dispatches to the right importer for the input format. The
// returned note, when non-empty, is a human-readable summary of what a learner
// kept and dropped (the access-log path reports its coverage; spec conversions
// have nothing to add).
func importScenario(data []byte, format, name string) (scenariofile.Scenario, string, error) {
	switch detectFormat(format, name, data) {
	case "openapi":
		sc, err := importer.FromOpenAPI(data)
		return sc, "", err
	case "har":
		sc, err := importer.FromHAR(data)
		return sc, "", err
	case "accesslog":
		sc, stats, err := importer.FromAccessLog(data)
		if err != nil {
			return scenariofile.Scenario{}, "", err
		}
		note := fmt.Sprintf("learned %d endpoint(s) from %d request(s) across %d session(s), %d client(s)",
			len(sc.Templates), stats.Requests, stats.Sessions, stats.Clients)
		if stats.DroppedEndpoints > 0 {
			note += fmt.Sprintf("; folded %d colder endpoint(s) beyond the graph cap", stats.DroppedEndpoints)
		}
		if stats.Skipped > 0 {
			note += fmt.Sprintf("; skipped %d unusable line(s)", stats.Skipped)
		}
		return sc, note, nil
	default:
		return scenariofile.Scenario{}, "", fmt.Errorf("unknown format %q; use --format openapi|har|accesslog", format)
	}
}

// importRunSpec converts an uploaded API description or access log into a
// RunSpec for the web import endpoint (POST /api/import). That endpoint only
// returns the graph, templates, start and maxSteps — the target env is
// discarded — so inputs that name no host (access logs, server-less OpenAPI
// specs) get a placeholder target instead of failing the expansion.
func importRunSpec(data []byte, format string) (runspec.RunSpec, error) {
	sc, note, err := importScenario(data, format, "")
	if err != nil {
		return runspec.RunSpec{}, err
	}
	if note != "" {
		slog.Info("import", "note", note)
	}
	if sc.Target == "" {
		sc.Target = "http://localhost:9000"
	}
	return scenariofile.Expand(sc)
}

// detectFormat resolves an explicit --format, else infers it from the filename
// extension and finally the content. A HAR is JSON with a top-level "log" object
// holding an "entries" array; OpenAPI/Swagger has "openapi"/"swagger"/"paths".
// Content sniffing is structural (parse the JSON and inspect keys) so it is
// robust to whitespace and key order — a real browser HAR was being misread as
// OpenAPI when uploaded without its .har name. A substring guess remains as a
// last resort for non-JSON (YAML) OpenAPI.
func detectFormat(format, name string, data []byte) string {
	if format != "" && format != "auto" {
		return format
	}
	lower := strings.ToLower(name)
	if strings.HasSuffix(lower, ".har") {
		return "har"
	}
	if strings.HasSuffix(lower, ".log") || strings.HasSuffix(lower, ".jsonl") {
		return "accesslog"
	}
	var probe struct {
		Log *struct {
			Entries []json.RawMessage `json:"entries"`
		} `json:"log"`
		OpenAPI json.RawMessage            `json:"openapi"`
		Swagger json.RawMessage            `json:"swagger"`
		Paths   map[string]json.RawMessage `json:"paths"`
	}
	if json.Unmarshal(data, &probe) == nil {
		// Check the OpenAPI markers first: a real OpenAPI doc never carries a
		// top-level log/entries, so this keeps a (pathological) spec that happens
		// to mention one from being mistaken for a HAR.
		switch {
		case len(probe.OpenAPI) > 0 || len(probe.Swagger) > 0 || probe.Paths != nil:
			return "openapi"
		case probe.Log != nil && probe.Log.Entries != nil:
			return "har"
		}
	}
	// An access log is line-oriented, so it never parses as one JSON document:
	// probe the first non-empty line instead (a combined-format line or a JSON
	// log record). This runs before the HAR substring guess so a JSON log line
	// that merely mentions "log" is not mistaken for a HAR.
	if importer.LooksLikeAccessLog(data) {
		return "accesslog"
	}
	if bytes.Contains(data, []byte(`"log"`)) && bytes.Contains(data, []byte(`"entries"`)) {
		return "har"
	}
	return "openapi"
}
