package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"github.com/chordpli/tmula/server/internal/api"
	"github.com/chordpli/tmula/server/internal/importer"
	"github.com/chordpli/tmula/server/internal/runspec"
	"github.com/chordpli/tmula/server/internal/scenariofile"
)

// initScenario implements `tmula init`: scaffold a scenario file from an
// existing API description (OpenAPI or HAR) so the user starts from their real
// endpoints instead of a blank page.
func initScenario(args []string) error {
	fs := flag.NewFlagSet("tmula init", flag.ContinueOnError)
	var (
		from   = fs.String("from", "", "input to import: an OpenAPI spec, a HAR capture, or an access log")
		format = fs.String("format", "auto", "input format: auto | openapi | har | accesslog")
		out    = fs.String("out", "", "write the scenario here (default: stdout)")
		target = fs.String("target", "", "override the target base URL")
	)
	fs.Usage = func() {
		fmt.Fprint(os.Stderr, "usage: tmula init --from <openapi.yaml|session.har|access.log> [--out scenario.yaml]\n\n")
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *from == "" {
		fs.Usage()
		return fmt.Errorf("--from is required")
	}

	data, err := os.ReadFile(*from)
	if err != nil {
		return fmt.Errorf("read %q: %w", *from, err)
	}
	sc, note, err := importScenario(data, *format, *from)
	if err != nil {
		return err
	}
	if note != "" {
		fmt.Fprintln(os.Stderr, note)
	}
	if *target != "" {
		sc.Target = *target
	}
	if sc.Target == "" {
		return fmt.Errorf("could not determine a target URL from the input; pass --target")
	}

	doc, err := importer.Marshal(sc)
	if err != nil {
		return err
	}
	review := "# Review the steps (fill in path params and bodies), then:  tmula run <this file>\n"
	count, unit := len(sc.Flow), "steps"
	if sc.Graph != nil {
		review = "# Review the graph (weights are observed transition shares; template paths\n" +
			"# carry sample observed values), then:  tmula run <this file>\n"
		count, unit = len(sc.Graph.Nodes), "nodes"
	}
	header := "# Generated by `tmula init` from " + filepath.Base(*from) + ".\n" + review
	doc = append([]byte(header), doc...)

	if *out == "" {
		_, err = os.Stdout.Write(doc)
		return err
	}
	if err := os.WriteFile(*out, doc, 0o644); err != nil {
		return fmt.Errorf("write %q: %w", *out, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d %s) — run it with:  tmula run %s\n", *out, count, unit, *out)
	return nil
}

// importScenario dispatches to the right importer for the input format. The
// returned note, when non-empty, is a human-readable summary of what a learner
// kept and dropped (the access-log path reports its coverage; spec conversions
// have nothing to add).
func importScenario(data []byte, format, name string) (scenariofile.Scenario, string, error) {
	sc, stats, err := importScenarioStats(data, format, name)
	if err != nil || stats == nil {
		return sc, "", err
	}
	return sc, accessLogNote(sc, *stats), nil
}

// importScenarioStats is importScenario's stats-carrying core: the access-log
// path returns the learner's coverage report, spec conversions (OpenAPI/HAR)
// return nil — they have no coverage to report.
func importScenarioStats(data []byte, format, name string) (scenariofile.Scenario, *importer.AccessLogStats, error) {
	switch detectFormat(format, name, data) {
	case "openapi":
		sc, err := importer.FromOpenAPI(data)
		return sc, nil, err
	case "har":
		sc, err := importer.FromHAR(data)
		return sc, nil, err
	case "accesslog":
		sc, stats, err := importer.FromAccessLog(data)
		if err != nil {
			return scenariofile.Scenario{}, nil, err
		}
		return sc, &stats, nil
	default:
		return scenariofile.Scenario{}, nil, fmt.Errorf("unknown format %q; use --format openapi|har|accesslog", format)
	}
}

// noteSkippedSampleCap bounds how many skipped-line examples the init note
// shows; the full sample list still travels with the web import stats.
const noteSkippedSampleCap = 3

// accessLogNote renders the learner's coverage for `tmula init`'s stderr: what
// was kept, which format profile detection resolved (so a misdetection across
// the six supported formats is visible instead of silent), and the first
// skipped lines with their numbers and reasons.
func accessLogNote(sc scenariofile.Scenario, stats importer.AccessLogStats) string {
	note := fmt.Sprintf("learned %d endpoint(s) from %d request(s) across %d session(s), %d client(s)",
		len(sc.Templates), stats.Requests, stats.Sessions, stats.Clients)
	if stats.Format != "" {
		note += fmt.Sprintf(" (%s format)", stats.Format)
	}
	if stats.DroppedEndpoints > 0 {
		note += fmt.Sprintf("; folded %d colder endpoint(s) beyond the graph cap", stats.DroppedEndpoints)
	}
	if stats.Skipped > 0 {
		note += fmt.Sprintf("; skipped %d unusable line(s)", stats.Skipped)
	}
	samples := stats.SkippedSamples
	if len(samples) > noteSkippedSampleCap {
		samples = samples[:noteSkippedSampleCap]
	}
	for _, s := range samples {
		note += fmt.Sprintf("\n  line %d: %s", s.Line, s.Reason)
	}
	if rest := len(stats.SkippedSamples) - len(samples); rest > 0 {
		note += fmt.Sprintf("\n  … and %d more sampled line(s)", rest)
	}
	return note
}

// importRunSpecWithStats converts an uploaded API description or access log
// into a RunSpec plus optional coverage stats for the web import endpoint
// (POST /api/import). The endpoint only returns the graph, templates, start
// and maxSteps — the target env is discarded — so inputs that name no host
// (access logs, server-less OpenAPI specs) get a placeholder target instead of
// failing the expansion. Access-log imports carry the learner's coverage
// mapped onto the wire type; spec conversions return nil stats, which omits
// the field from the response.
func importRunSpecWithStats(data []byte, format string) (runspec.RunSpec, *api.ImportStats, error) {
	sc, stats, err := importScenarioStats(data, format, "")
	if err != nil {
		return runspec.RunSpec{}, nil, err
	}
	if sc.Target == "" {
		sc.Target = "http://localhost:9000"
	}
	spec, err := scenariofile.Expand(sc)
	if err != nil {
		return runspec.RunSpec{}, nil, err
	}
	if stats == nil {
		return spec, nil, nil
	}
	// Keep the server-side breadcrumb the legacy importer logged: the response
	// carries the stats, but an operator tailing the engine log still sees what
	// an upload learned.
	slog.Info("import", "note", accessLogNote(sc, *stats))
	return spec, toImportStats(*stats), nil
}

// toImportStats maps the learner's coverage report onto the wire type
// field-for-field. The api package cannot name the importer's type directly
// (the injection keeps those packages decoupled), so the mapping lives here.
func toImportStats(stats importer.AccessLogStats) *api.ImportStats {
	out := &api.ImportStats{
		Format:           stats.Format,
		Requests:         stats.Requests,
		Skipped:          stats.Skipped,
		Sessions:         stats.Sessions,
		Clients:          stats.Clients,
		DroppedEndpoints: stats.DroppedEndpoints,
	}
	for _, s := range stats.SkippedSamples {
		out.SkippedSamples = append(out.SkippedSamples, api.ImportSkippedSample{
			Line:   s.Line,
			Text:   s.Text,
			Reason: s.Reason,
		})
	}
	return out
}

// detectFormat resolves an explicit --format, else infers it from the filename
// extension and finally the content. A HAR is JSON with a top-level "log" object
// holding an "entries" array; OpenAPI/Swagger has "openapi"/"swagger"/"paths".
// Content sniffing is structural (parse the JSON and inspect keys) so it is
// robust to whitespace and key order — a real browser HAR was being misread as
// OpenAPI when uploaded without its .har name. A substring guess remains as a
// last resort for non-JSON (YAML) OpenAPI.
func detectFormat(format, name string, data []byte) string {
	if format != "" && format != "auto" {
		return format
	}
	lower := strings.ToLower(name)
	if strings.HasSuffix(lower, ".har") {
		return "har"
	}
	if strings.HasSuffix(lower, ".log") || strings.HasSuffix(lower, ".jsonl") {
		return "accesslog"
	}
	var probe struct {
		Log *struct {
			Entries []json.RawMessage `json:"entries"`
		} `json:"log"`
		OpenAPI json.RawMessage            `json:"openapi"`
		Swagger json.RawMessage            `json:"swagger"`
		Paths   map[string]json.RawMessage `json:"paths"`
	}
	if json.Unmarshal(data, &probe) == nil {
		// Check the OpenAPI markers first: a real OpenAPI doc never carries a
		// top-level log/entries, so this keeps a (pathological) spec that happens
		// to mention one from being mistaken for a HAR.
		switch {
		case len(probe.OpenAPI) > 0 || len(probe.Swagger) > 0 || probe.Paths != nil:
			return "openapi"
		case probe.Log != nil && probe.Log.Entries != nil:
			return "har"
		}
	}
	// An access log is line-oriented, so it never parses as one JSON document:
	// probe the first non-empty line instead (a combined-format line or a JSON
	// log record). This runs before the HAR substring guess so a JSON log line
	// that merely mentions "log" is not mistaken for a HAR.
	if importer.LooksLikeAccessLog(data) {
		return "accesslog"
	}
	if bytes.Contains(data, []byte(`"log"`)) && bytes.Contains(data, []byte(`"entries"`)) {
		return "har"
	}
	return "openapi"
}
