// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cluster.proto

// Package cluster.v1 is the wire contract between a load-test master and its
// workers. The master splits a run's virtual users across workers; each worker
// executes its shard and streams per-step results back for aggregation.

package clusterpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterService_RunShard_FullMethodName        = "/cluster.v1.ClusterService/RunShard"
	ClusterService_RunShardSummary_FullMethodName = "/cluster.v1.ClusterService/RunShardSummary"
	ClusterService_Ping_FullMethodName            = "/cluster.v1.ClusterService/Ping"
)

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClusterService is served by every worker. A master dials each registered
// worker and drives shards through it.
type ClusterServiceClient interface {
	// RunShard asks the worker to execute its assigned slice of virtual users and
	// stream one ShardResult per request the users make. The stream completes
	// when the shard finishes (or the context is cancelled).
	RunShard(ctx context.Context, in *RunShardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardResult], error)
	// RunShardSummary executes the same shard as RunShard but, instead of
	// streaming one message per request, aggregates the whole shard on the worker
	// and returns a single compact, mergeable summary. The master folds the
	// per-worker summaries together, trading per-request fidelity for bounded
	// network and memory at millions of requests — the same shard, summarized at
	// the edge rather than streamed.
	RunShardSummary(ctx context.Context, in *RunShardRequest, opts ...grpc.CallOption) (*ShardSummary, error)
	// Ping is a liveness probe used to confirm a worker is reachable.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) RunShard(ctx context.Context, in *RunShardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterService_ServiceDesc.Streams[0], ClusterService_RunShard_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunShardRequest, ShardResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterService_RunShardClient = grpc.ServerStreamingClient[ShardResult]

func (c *clusterServiceClient) RunShardSummary(ctx context.Context, in *RunShardRequest, opts ...grpc.CallOption) (*ShardSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShardSummary)
	err := c.cc.Invoke(ctx, ClusterService_RunShardSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, ClusterService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
// All implementations must embed UnimplementedClusterServiceServer
// for forward compatibility.
//
// ClusterService is served by every worker. A master dials each registered
// worker and drives shards through it.
type ClusterServiceServer interface {
	// RunShard asks the worker to execute its assigned slice of virtual users and
	// stream one ShardResult per request the users make. The stream completes
	// when the shard finishes (or the context is cancelled).
	RunShard(*RunShardRequest, grpc.ServerStreamingServer[ShardResult]) error
	// RunShardSummary executes the same shard as RunShard but, instead of
	// streaming one message per request, aggregates the whole shard on the worker
	// and returns a single compact, mergeable summary. The master folds the
	// per-worker summaries together, trading per-request fidelity for bounded
	// network and memory at millions of requests — the same shard, summarized at
	// the edge rather than streamed.
	RunShardSummary(context.Context, *RunShardRequest) (*ShardSummary, error)
	// Ping is a liveness probe used to confirm a worker is reachable.
	Ping(context.Context, *PingRequest) (*PingReply, error)
	mustEmbedUnimplementedClusterServiceServer()
}

// UnimplementedClusterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterServiceServer struct{}

func (UnimplementedClusterServiceServer) RunShard(*RunShardRequest, grpc.ServerStreamingServer[ShardResult]) error {
	return status.Error(codes.Unimplemented, "method RunShard not implemented")
}
func (UnimplementedClusterServiceServer) RunShardSummary(context.Context, *RunShardRequest) (*ShardSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method RunShardSummary not implemented")
}
func (UnimplementedClusterServiceServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {}
func (UnimplementedClusterServiceServer) testEmbeddedByValue()                        {}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	// If the following call panics, it indicates UnimplementedClusterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_RunShard_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunShardRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusterServiceServer).RunShard(m, &grpc.GenericServerStream[RunShardRequest, ShardResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterService_RunShardServer = grpc.ServerStreamingServer[ShardResult]

func _ClusterService_RunShardSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).RunShardSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_RunShardSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).RunShardSummary(ctx, req.(*RunShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.v1.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunShardSummary",
			Handler:    _ClusterService_RunShardSummary_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _ClusterService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunShard",
			Handler:       _ClusterService_RunShard_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cluster.proto",
}
