// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cluster.proto

// Package cluster.v1 is the wire contract between a load-test master and its
// workers. The master splits a run's virtual users across workers; each worker
// executes its shard and streams per-step results back for aggregation.

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunShardRequest is fully self-contained: the scenario graph, API templates
// and target are carried as a single JSON document (spec_json) so the domain
// model is not duplicated in protobuf. The remaining fields parameterize which
// users this worker owns and how they walk the graph.
type RunShardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// spec_json is the JSON encoding of the shared cluster.ShardSpec.
	SpecJson string `protobuf:"bytes,1,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	// user_offset is the index of the first virtual user this shard owns. It both
	// names the users (user-<offset+i>) and seeds the per-user RNG, so the global
	// run stays deterministic regardless of how users were partitioned.
	UserOffset int32 `protobuf:"varint,2,opt,name=user_offset,json=userOffset,proto3" json:"user_offset,omitempty"`
	// user_count is how many virtual users this shard runs.
	UserCount int32 `protobuf:"varint,3,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	// seed is the run-wide base seed; per-user seed is seed + global user index.
	Seed int64 `protobuf:"varint,4,opt,name=seed,proto3" json:"seed,omitempty"`
	// max_steps bounds each user's walk length.
	MaxSteps int32 `protobuf:"varint,5,opt,name=max_steps,json=maxSteps,proto3" json:"max_steps,omitempty"`
	// start_node is the graph node every user starts from.
	StartNode     string `protobuf:"bytes,6,opt,name=start_node,json=startNode,proto3" json:"start_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunShardRequest) Reset() {
	*x = RunShardRequest{}
	mi := &file_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunShardRequest) ProtoMessage() {}

func (x *RunShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunShardRequest.ProtoReflect.Descriptor instead.
func (*RunShardRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *RunShardRequest) GetSpecJson() string {
	if x != nil {
		return x.SpecJson
	}
	return ""
}

func (x *RunShardRequest) GetUserOffset() int32 {
	if x != nil {
		return x.UserOffset
	}
	return 0
}

func (x *RunShardRequest) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *RunShardRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *RunShardRequest) GetMaxSteps() int32 {
	if x != nil {
		return x.MaxSteps
	}
	return 0
}

func (x *RunShardRequest) GetStartNode() string {
	if x != nil {
		return x.StartNode
	}
	return ""
}

// ShardResult is one observed request outcome from a worker. A non-2xx status
// is reported as data (not an error); error_class is set for transport/render
// failures or when no response was produced.
type ShardResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id is the virtual user that made the request (user-<global index>).
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// api_id is the API template id bound to the visited node, if any.
	ApiId string `protobuf:"bytes,2,opt,name=api_id,json=apiId,proto3" json:"api_id,omitempty"`
	// status_code is the HTTP status, or 0 when no response was received.
	StatusCode int32 `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// latency_ms is the client-observed round-trip latency in milliseconds.
	LatencyMs float64 `protobuf:"fixed64,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// error_class names the failure class (empty on success).
	ErrorClass    string `protobuf:"bytes,5,opt,name=error_class,json=errorClass,proto3" json:"error_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardResult) Reset() {
	*x = ShardResult{}
	mi := &file_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardResult) ProtoMessage() {}

func (x *ShardResult) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardResult.ProtoReflect.Descriptor instead.
func (*ShardResult) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *ShardResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShardResult) GetApiId() string {
	if x != nil {
		return x.ApiId
	}
	return ""
}

func (x *ShardResult) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ShardResult) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ShardResult) GetErrorClass() string {
	if x != nil {
		return x.ErrorClass
	}
	return ""
}

// PingRequest carries an optional caller-chosen nonce echoed back in the reply.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// PingReply echoes the request nonce and identifies the responding worker.
type PingReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Nonce string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// worker_id identifies the responding worker (may be empty if unset).
	WorkerId      string `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *PingReply) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *PingReply) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\n" +
	"cluster.v1\"\xbe\x01\n" +
	"\x0fRunShardRequest\x12\x1b\n" +
	"\tspec_json\x18\x01 \x01(\tR\bspecJson\x12\x1f\n" +
	"\vuser_offset\x18\x02 \x01(\x05R\n" +
	"userOffset\x12\x1d\n" +
	"\n" +
	"user_count\x18\x03 \x01(\x05R\tuserCount\x12\x12\n" +
	"\x04seed\x18\x04 \x01(\x03R\x04seed\x12\x1b\n" +
	"\tmax_steps\x18\x05 \x01(\x05R\bmaxSteps\x12\x1d\n" +
	"\n" +
	"start_node\x18\x06 \x01(\tR\tstartNode\"\x9e\x01\n" +
	"\vShardResult\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06api_id\x18\x02 \x01(\tR\x05apiId\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x01R\tlatencyMs\x12\x1f\n" +
	"\verror_class\x18\x05 \x01(\tR\n" +
	"errorClass\"#\n" +
	"\vPingRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\">\n" +
	"\tPingReply\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId2\x8c\x01\n" +
	"\x0eClusterService\x12B\n" +
	"\bRunShard\x12\x1b.cluster.v1.RunShardRequest\x1a\x17.cluster.v1.ShardResult0\x01\x126\n" +
	"\x04Ping\x12\x17.cluster.v1.PingRequest\x1a\x15.cluster.v1.PingReplyB6Z4github.com/chordpli/tmula/internal/cluster/clusterpbb\x06proto3"

var (
	file_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_rawDescData []byte
)

func file_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_rawDescData
}

var file_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cluster_proto_goTypes = []any{
	(*RunShardRequest)(nil), // 0: cluster.v1.RunShardRequest
	(*ShardResult)(nil),     // 1: cluster.v1.ShardResult
	(*PingRequest)(nil),     // 2: cluster.v1.PingRequest
	(*PingReply)(nil),       // 3: cluster.v1.PingReply
}
var file_cluster_proto_depIdxs = []int32{
	0, // 0: cluster.v1.ClusterService.RunShard:input_type -> cluster.v1.RunShardRequest
	2, // 1: cluster.v1.ClusterService.Ping:input_type -> cluster.v1.PingRequest
	1, // 2: cluster.v1.ClusterService.RunShard:output_type -> cluster.v1.ShardResult
	3, // 3: cluster.v1.ClusterService.Ping:output_type -> cluster.v1.PingReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
		MessageInfos:      file_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
