package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/chordpli/tmula/internal/importer"
	"github.com/chordpli/tmula/internal/scenariofile"
)

// initScenario implements `tmula init`: scaffold a scenario file from an
// existing API description (OpenAPI or HAR) so the user starts from their real
// endpoints instead of a blank page.
func initScenario(args []string) error {
	fs := flag.NewFlagSet("tmula init", flag.ContinueOnError)
	var (
		from   = fs.String("from", "", "API description to import: an OpenAPI or HAR file")
		format = fs.String("format", "auto", "input format: auto | openapi | har")
		out    = fs.String("out", "", "write the scenario here (default: stdout)")
		target = fs.String("target", "", "override the target base URL")
	)
	fs.Usage = func() {
		fmt.Fprint(os.Stderr, "usage: tmula init --from <openapi.yaml|session.har> [--out scenario.yaml]\n\n")
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *from == "" {
		fs.Usage()
		return fmt.Errorf("--from is required")
	}

	data, err := os.ReadFile(*from)
	if err != nil {
		return fmt.Errorf("read %q: %w", *from, err)
	}
	sc, err := importScenario(data, *format, *from)
	if err != nil {
		return err
	}
	if *target != "" {
		sc.Target = *target
	}
	if sc.Target == "" {
		return fmt.Errorf("could not determine a target URL from the input; pass --target")
	}

	doc, err := importer.Marshal(sc)
	if err != nil {
		return err
	}
	header := "# Generated by `tmula init` from " + filepath.Base(*from) + ".\n" +
		"# Review the steps (fill in path params and bodies), then:  tmula run <this file>\n"
	doc = append([]byte(header), doc...)

	if *out == "" {
		_, err = os.Stdout.Write(doc)
		return err
	}
	if err := os.WriteFile(*out, doc, 0o644); err != nil {
		return fmt.Errorf("write %q: %w", *out, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d steps) — run it with:  tmula run %s\n", *out, len(sc.Flow), *out)
	return nil
}

// importScenario dispatches to the right importer for the input format.
func importScenario(data []byte, format, name string) (scenariofile.Scenario, error) {
	switch detectFormat(format, name, data) {
	case "openapi":
		return importer.FromOpenAPI(data)
	case "har":
		return importer.FromHAR(data)
	default:
		return scenariofile.Scenario{}, fmt.Errorf("unknown format %q; use --format openapi|har", format)
	}
}

// detectFormat resolves an explicit --format, else infers it from the filename
// and content (HAR is JSON with a top-level log/entries; anything else is
// treated as OpenAPI).
func detectFormat(format, name string, data []byte) string {
	if format != "" && format != "auto" {
		return format
	}
	if strings.HasSuffix(strings.ToLower(name), ".har") {
		return "har"
	}
	if bytes.Contains(data, []byte(`"log"`)) && bytes.Contains(data, []byte(`"entries"`)) {
		return "har"
	}
	return "openapi"
}
